import React from 'react';
import styled from 'styled-components';
import Blooddonor from './images/Blooddonor.jpeg';
import Navbar from './Navbar';
import FooterComponent from './FooterComponent';

const AboutSection = styled.section`
  padding: 40px;
  max-width: 800px;
  margin: auto;
  text-align: center;
`;

const AboutImage = styled.img`
  width: 100%;
  max-width: 600px;
  margin: 20px 0;
`;

const AboutUs = () => {
  return (
    <div>
    <Navbar />
    <AboutSection>
      
      <h1>About Us</h1>
      <p>
      Our platform addresses the critical issue of patients struggling to find blood. By connecting donors, patients, hospitals, and blood camp organizers, we streamline the donation process and incentivize donors with coupons.
        The main purpose is to get more Blood Donation. To attract more donors we are providing some rewards to the donors. Hospitals,Blood Camp,Blood Centers
        are receiving more blood donors. Hospitals and Blood Center are getting access to live donors in cases of Emergencies.
        Donors are getting rewards of there choice after donating blood.Donors can also register themselves as Live Donors. 
      </p>
      <AboutImage src={Blooddonor} alt="Blood donation" />
      <p>
      In the mission to save lives through blood donation, there are numerous heroes whose contributions often go unnoticed. Among these are the generous companies that donate coupons to incentivize and reward blood donors. These corporate partners play a crucial role in our blood donation project, enhancing the donor experience and promoting a culture of giving within the community.

These companies, spanning various industries from retail to hospitality, offer a range of coupons that provide tangible rewards to those who donate blood. From discount vouchers for popular restaurants to exclusive deals on essential goods, these incentives not only thank donors for their selflessness but also encourage more people to participate in blood donation drives. The impact of their contributions is far-reaching, as each coupon represents a token of gratitude that can make the act of donating blood a more rewarding experience.

The involvement of these companies goes beyond mere corporate social responsibility; it embodies a commitment to community welfare and public health. By partnering with our blood donation project, they help bridge the gap between donor motivation and community needs. Their support ensures a steady supply of blood, which is vital for emergency surgeries, medical treatments, and life-saving procedures. These companies understand that their donations of coupons are not just about marketing but about fostering a culture of care and altruism.

Moreover, the partnership between our project and these companies highlights the power of collaboration in addressing critical health challenges. It showcases how businesses can leverage their resources and reach to make a positive impact on society. The visibility and goodwill generated by these coupon donations also enhance the public image of the contributing companies, demonstrating their role as responsible and compassionate members of the community.

In conclusion, the companies that donate coupons to our blood donation project are indispensable stakeholders whose contributions significantly enhance our efforts. Their generosity not only rewards our donors but also inspires a broader community to engage in the life-saving act of blood donation. As we continue to strive for a healthier and more supportive society, we extend our heartfelt gratitude to these corporate partners for their unwavering support and commitment to saving lives
      </p>
    </AboutSection>
    <FooterComponent />
    </div>
  );
};

export default AboutUs;
